-file("/home/fredrik.gustafsson2/git/klarna/OTP/R15B03-1/../../OTP/install/R15B03-1/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(gelo_scanner).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./gelo_scanner.xrl", 42).

-export([scan/1]).

scan(String) -> {ok, Tokens, _EndLine} = ?MODULE:string(String), Tokens.
-file("/home/fredrik.gustafsson2/git/klarna/OTP/R15B03-1/../../OTP/install/R15B03-1/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("./gelo_scanner.erl", 280).
yystate() -> 78.

yystate(81, [101|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,81};
yystate(80, [10|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line+1, Tlen+1, 29, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(80, Ics, Line, Tlen+1, 29, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(80, Ics, Line, Tlen+1, 29, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line,80};
yystate(79, [116|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 17, Tlen);
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,79};
yystate(78, [125|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [123|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [118|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [117|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [116|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [115|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [114|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [112|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [113|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [111|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [109|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [110|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [108|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [106|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [107|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [105|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [104|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [103|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [102|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [101|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [100|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [99|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [98|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [97|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [64|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [62|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [61|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [60|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [59|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [47|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [46|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [45|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [44|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [43|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [42|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [41|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [40|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [36|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [34|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [33|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [10|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line+1, Tlen+1, 17, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(80, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(80, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,78};
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 4, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,77};
yystate(76, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,75};
yystate(74, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(73, [102|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 17, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,73};
yystate(72, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [117|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,71};
yystate(70, [97|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 17, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,70};
yystate(69, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 8, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 8, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 8, Tlen);
yystate(69, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 8, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,69};
yystate(68, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(68, [C|Ics], Line, Tlen, Action, Alen) when C >= 35 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,68};
yystate(67, [110|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,67};
yystate(66, [114|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 17, Tlen);
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,66};
yystate(65, [116|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 17, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,65};
yystate(64, [34|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 19, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(68, Ics, Line, Tlen+1, 19, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(68, Ics, Line, Tlen+1, 19, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(68, Ics, Line, Tlen+1, 19, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line,64};
yystate(63, [99|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, [97|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, [98|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,63};
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 2, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,62};
yystate(61, [115|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,61};
yystate(60, [34|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(68, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(68, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 35 ->
    yystate(68, Ics, Line, Tlen+1, 18, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,60};
yystate(59, [116|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,59};
yystate(58, [104|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 17, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,58};
yystate(57, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 7, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,57};
yystate(56, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 91, C =< 94 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(56, [C|Ics], Line, Tlen, Action, Alen) when C >= 123 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(56, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,56};
yystate(55, [105|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 17, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,55};
yystate(54, [114|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,54};
yystate(53, [103|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(51, [111|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,51};
yystate(50, [101|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 17, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,50};
yystate(49, [111|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [105|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 110 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,49};
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(48, Ics, Line, Tlen+1, 15, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,48};
yystate(47, [110|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,47};
yystate(46, [97|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 17, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,46};
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 11, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 11, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 11, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 11, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,45};
yystate(44, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 3, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,43};
yystate(42, [100|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 17, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,42};
yystate(41, [114|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,41};
yystate(40, [61|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 21, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line,40};
yystate(39, [108|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,39};
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,38};
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 14, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 14, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 14, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 14, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,37};
yystate(36, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line};
yystate(35, [115|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,35};
yystate(34, [112|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 111 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,34};
yystate(33, [101|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 17, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,33};
yystate(32, [61|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 20, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,32};
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 17, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,31};
yystate(30, [97|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,30};
yystate(29, [118|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 117 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,29};
yystate(28, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 5, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 5, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 5, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 5, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,27};
yystate(26, [119|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 17, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 118 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 120, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,26};
yystate(25, [105|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,25};
yystate(24, [61|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 22, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line,24};
yystate(23, [111|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,23};
yystate(22, [110|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 17, Tlen);
yystate(22, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(22, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(22, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,22};
yystate(21, [101|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(19, [110|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,19};
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 12, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 12, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 12, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 12, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,18};
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 1, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,17};
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,16};
yystate(15, [115|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,15};
yystate(14, [110|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,14};
yystate(13, [110|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 17, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,13};
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 10, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 10, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 10, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 10, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,12};
yystate(11, [111|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,11};
yystate(10, [100|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 17, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,10};
yystate(9, [114|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,9};
yystate(8, [100|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,8};
yystate(7, [108|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 17, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,7};
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 13, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 13, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 13, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 13, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,6};
yystate(5, [117|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,5};
yystate(4, [110|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,4};
yystate(3, [101|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,3};
yystate(2, [101|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,2};
yystate(1, [116|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [99|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [97|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [98|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 115 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,1};
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 6, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(16, Ics, Line, Tlen+1, 6, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(16, Ics, Line, Tlen+1, 6, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(16, Ics, Line, Tlen+1, 6, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, _) ->
    yyaction_29();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("./gelo_scanner.xrl", 9).
yyaction_0(TokenLine) ->
     { token, { thread, TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("./gelo_scanner.xrl", 10).
yyaction_1(TokenLine) ->
     { token, { variable, TokenLine } } .

-compile({inline,yyaction_2/1}).
-file("./gelo_scanner.xrl", 11).
yyaction_2(TokenLine) ->
     { token, { variable, TokenLine } } .

-compile({inline,yyaction_3/1}).
-file("./gelo_scanner.xrl", 12).
yyaction_3(TokenLine) ->
     { token, { function, TokenLine } } .

-compile({inline,yyaction_4/1}).
-file("./gelo_scanner.xrl", 13).
yyaction_4(TokenLine) ->
     { token, { 'if', TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("./gelo_scanner.xrl", 14).
yyaction_5(TokenLine) ->
     { token, { else, TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("./gelo_scanner.xrl", 15).
yyaction_6(TokenLine) ->
     { token, { console, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("./gelo_scanner.xrl", 16).
yyaction_7(TokenLine) ->
     { token, { log, TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("./gelo_scanner.xrl", 17).
yyaction_8(TokenLine) ->
     { token, { list, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("./gelo_scanner.xrl", 18).
yyaction_9(TokenLine) ->
     { token, { get, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("./gelo_scanner.xrl", 19).
yyaction_10(TokenLine) ->
     { token, { 'and', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("./gelo_scanner.xrl", 20).
yyaction_11(TokenLine) ->
     { token, { 'or', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("./gelo_scanner.xrl", 21).
yyaction_12(TokenLine) ->
     { token, { spawn, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("./gelo_scanner.xrl", 22).
yyaction_13(TokenLine) ->
     { token, { send, TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("./gelo_scanner.xrl", 23).
yyaction_14(TokenLine) ->
     { token, { recv, TokenLine } } .

-compile({inline,yyaction_15/2}).
-file("./gelo_scanner.xrl", 24).
yyaction_15(TokenChars, TokenLine) ->
     { token, { integer, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/2}).
-file("./gelo_scanner.xrl", 25).
yyaction_16(TokenChars, TokenLine) ->
     { token, { atomic, TokenLine, TokenChars } } .

-compile({inline,yyaction_17/2}).
-file("./gelo_scanner.xrl", 26).
yyaction_17(TokenChars, TokenLine) ->
     { token, { name, TokenLine, TokenChars } } .

-compile({inline,yyaction_18/2}).
-file("./gelo_scanner.xrl", 27).
yyaction_18(TokenChars, TokenLine) ->
     { token, { string, TokenLine, TokenChars } } .

-compile({inline,yyaction_19/2}).
-file("./gelo_scanner.xrl", 28).
yyaction_19(TokenChars, TokenLine) ->
     { token, { string, TokenLine, TokenChars } } .

-compile({inline,yyaction_20/2}).
-file("./gelo_scanner.xrl", 29).
yyaction_20(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("./gelo_scanner.xrl", 30).
yyaction_21(TokenLine) ->
     { token, { lt, TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("./gelo_scanner.xrl", 31).
yyaction_22(TokenLine) ->
     { token, { gt, TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("./gelo_scanner.xrl", 32).
yyaction_23(TokenLine) ->
     { token, { eq, TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("./gelo_scanner.xrl", 33).
yyaction_24(TokenLine) ->
     { token, { neq, TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("./gelo_scanner.xrl", 34).
yyaction_25(TokenLine) ->
     { token, { leq, TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("./gelo_scanner.xrl", 35).
yyaction_26(TokenLine) ->
     { token, { geq, TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("./gelo_scanner.xrl", 36).
yyaction_27(TokenLine) ->
     { token, { concat, TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("./gelo_scanner.xrl", 37).
yyaction_28(TokenLine) ->
     { token, { ext, TokenLine } } .

-compile({inline,yyaction_29/0}).
-file("./gelo_scanner.xrl", 38).
yyaction_29() ->
     skip_token .

-file("/home/fredrik.gustafsson2/git/klarna/OTP/R15B03-1/../../OTP/install/R15B03-1/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 282).
